In [1]:
import os
import sys
import numpy as np    

In [10]:
data_folder = '/data/ccc/dataset/snli_1.0'
out_folder = './data_snli'

label_set = set(["neutral", "entailment", "contradiction"])

for split in ["train", "dev", "test"]:
    src_out = open(os.path.join(out_folder, "src-" + split + ".txt"), "w")
    targ_out = open(os.path.join(out_folder, "targ-" + split + ".txt"), "w")
    label_out = open(os.path.join(out_folder, "label-" + split + ".txt"), "w")
    
    #for line in open(os.path.join(data_folder, "snli_1.0_" + split + ".txt"),"r"):
    with open(os.path.join(data_folder, "snli_1.0_" + split + ".txt"),"r") as f:
        for line in f:
            d = line.split("\t")
            label = d[0].strip()
            premise = " ".join(d[1].replace("(", "").replace(")", "").strip().split())
            hypothesis = " ".join(d[2].replace("(", "").replace(")", "").strip().split())
            if label in label_set:
                src_out.write(premise + "\n")
                targ_out.write(hypothesis + "\n")
                label_out.write(label + "\n")

    src_out.close()
    targ_out.close()
    label_out.close()

In [19]:
def show_res(filename):
    with open(os.path.join(out_folder, filename), "r") as f:
        lines = f.read().split('\n')
        for i in range(9):
            print(lines[i])

show_res("src-train.txt")

A person on a horse jumps over a broken down airplane .
A person on a horse jumps over a broken down airplane .
A person on a horse jumps over a broken down airplane .
Children smiling and waving at camera
Children smiling and waving at camera
Children smiling and waving at camera
A boy is jumping on skateboard in the middle of a red bridge .
A boy is jumping on skateboard in the middle of a red bridge .
A boy is jumping on skateboard in the middle of a red bridge .


In [22]:
show_res("targ-train.txt")

A person is training his horse for a competition .
A person is at a diner , ordering an omelette .
A person is outdoors , on a horse .
They are smiling at their parents
There are children present
The kids are frowning
The boy skates down the sidewalk .
The boy does a skateboarding trick .
The boy is wearing safety equipment .


In [23]:
show_res("label-train.txt")

neutral
contradiction
entailment
neutral
entailment
contradiction
contradiction
entailment
neutral


In [28]:
out = open('outfile.txt', "w")
items = [(1,2), (3,4)]
# items.sort()
for v, k in items:
    print(k, v, file=out)
    ##print >>out, k, v
out.close()

In [27]:
print("Hello world", file=open("foo.txt", "a"))

In [33]:
for _, (src_orig, targ_orig) in \
                enumerate(zip(open('foo.txt','r'), open('outfile.txt','r'))):
    print([src_orig.strip(), targ_orig.strip()])

['a', 'z']
['b', 'x']
['c', 'c']
['d', 'vb']
['e', 'n']


In [40]:
fname = '/data/charley/glove.840B.300d.txt'

word_vecs = {}
f = open(fname, 'r')
for line in f:
    d = line.split()
    word = d[0]
    vec = np.asarray(d[1:], dtype='float32')
#     vec = np.array(map(float, d[1:]))
    print(vec)
    break
f.close()
# vec

[-0.082752   0.67204   -0.14987   -0.064983   0.056491   0.40228
  0.0027747 -0.3311    -0.30691    2.0817     0.031819   0.013643
  0.30265    0.0071297 -0.5819    -0.2774    -0.062254   1.1451
 -0.24232    0.1235    -0.12243    0.33152   -0.006162  -0.30541
 -0.13057   -0.054601   0.037083  -0.070552   0.5893    -0.30385
  0.2898    -0.14653   -0.27052    0.37161    0.32031   -0.29125
  0.0052483 -0.13212   -0.052736   0.087349  -0.26668   -0.16897
  0.015162  -0.0083746 -0.14871    0.23413   -0.20719   -0.091386
  0.40075   -0.17223    0.18145    0.37586   -0.28682    0.37289
 -0.16185    0.18008    0.3032    -0.13216    0.18352    0.095759
  0.094916   0.008289   0.11761    0.34046    0.03677   -0.29077
  0.058303  -0.027814   0.082941   0.1862    -0.031494   0.27985
 -0.074412  -0.13762   -0.21866    0.18138    0.040855  -0.113
  0.24107    0.3657    -0.27525   -0.05684    0.34872    0.011884
  0.14517   -0.71395    0.48497    0.14807    0.62287    0.20599
  0.58379   -0.13438    

In [41]:
vec1 = vec / np.linalg.norm(vec)
vec1

array([-0.01624269,  0.13190901, -0.02941671, -0.01275496,  0.01108814,
        0.07896012,  0.00054462, -0.0649888 , -0.06024076,  0.4085992 ,
        0.00624548,  0.00267787,  0.0594046 ,  0.00139943, -0.1142162 ,
       -0.05444849, -0.01221931,  0.22476195, -0.04756293,  0.02424076,
       -0.02403074,  0.06507124, -0.00120949, -0.05994633, -0.02562847,
       -0.01071717,  0.00727871, -0.01384805,  0.11566868, -0.05964013,
        0.05688237, -0.02876113, -0.05309807,  0.07294016,  0.06287093,
       -0.05716699,  0.00103014, -0.02593271, -0.0103511 ,  0.01714499,
       -0.05234435, -0.03316569,  0.00297602, -0.00164378, -0.02918902,
        0.04595539, -0.04066756, -0.01793738,  0.07865981, -0.03380556,
        0.03561528,  0.07377437, -0.05629746,  0.0731914 , -0.03176816,
        0.03534637,  0.05951255, -0.02594056,  0.03602158,  0.01879572,
        0.01863026,  0.00162698,  0.02308467,  0.066826  ,  0.00721727,
       -0.05707277,  0.0114438 , -0.00545937,  0.01627978,  0.03

In [43]:
a = np.array([1,2,3])
np.linalg.norm(a)

3.7416573867739413

In [44]:
np.sqrt(14)

3.7416573867739413

In [46]:
import h5py
import numpy as np
import torch

fname = "./data_snli-train.hdf5"
f = h5py.File(fname, 'r')
source = torch.from_numpy(np.array(f['source'])) - 1
target = torch.from_numpy(np.array(f['target'])) - 1
label = torch.from_numpy(np.array(f['label'])) - 1

In [48]:
source.size()

torch.Size([549367, 1001])

In [58]:
source[100][:20]

tensor([   2,  104,  161, 2512,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0])

In [50]:
label.size()

torch.Size([549367])

In [51]:
label_size = torch.from_numpy(np.array(f['label_size']))
label_size

tensor([3])

In [52]:
source_l = torch.from_numpy(np.array(f['source_l']))
source_l.size()

torch.Size([18183])

In [59]:
source_l[100]

tensor(6)

In [61]:
549367/ 32

17167.71875

In [62]:
batch_idx = torch.from_numpy(np.array(f['batch_idx'])) - 1
batch_idx.size()

torch.Size([18183])

In [63]:
batch_l = torch.from_numpy(np.array(f['batch_l']))
batch_l.size()

torch.Size([18183])

In [66]:
batch_idx[:10]

tensor([ 0,  1,  3,  8, 15, 19, 21, 27, 28, 32])

In [65]:
batch_l[:10]

tensor([1, 2, 5, 7, 4, 2, 6, 1, 4, 1])

In [75]:
import torch.nn as nn

m = nn.Linear(10,2, bias=True)
x = torch.rand(3, 10)
y = m(x)
y.size()

torch.Size([3, 2])

In [76]:
m.bias is not None

True

In [87]:
class encoder(nn.Module):

    def __init__(self, num_embeddings, embedding_size, hidden_size, para_init):
        super(encoder, self).__init__()

        self.num_embeddings = num_embeddings
        self.embedding_size = embedding_size
        self.hidden_size = hidden_size
        self.para_init = para_init

        self.embedding = nn.Embedding(self.num_embeddings, self.embedding_size)
        self.input_linear = nn.Linear(
            self.embedding_size, self.hidden_size, bias=False)  # linear transformation
        for m in self.modules():
            if isinstance(m, nn.Linear):
                m.weight.data.normal_(0, self.para_init)
                # m.bias.data.uniform_(-0.01, 0.01)

    def forward(self, sent1, sent2):
        '''
               sent: batch_size x length (Long tensor)
        '''
        batch_size = sent1.size(0)
        sent1 = self.embedding(sent1)
        sent2 = self.embedding(sent2)

        sent1 = sent1.view(-1, self.embedding_size)
        sent2 = sent2.view(-1, self.embedding_size)

        sent1_linear = self.input_linear(sent1).view(
            batch_size, -1, self.hidden_size)
        sent2_linear = self.input_linear(sent2).view(
            batch_size, -1, self.hidden_size)

        return sent1_linear, sent2_linear
    
enc = encoder(1000, 300, 300, 0.01)
enc

>>  encoder(
  (embedding): Embedding(1000, 300)
  (input_linear): Linear(in_features=300, out_features=300, bias=False)
)
>>  Embedding(1000, 300)
>>  Linear(in_features=300, out_features=300, bias=False)


encoder(
  (embedding): Embedding(1000, 300)
  (input_linear): Linear(in_features=300, out_features=300, bias=False)
)

In [85]:
for m in enc.modules():
    print(type(m))

<class '__main__.encoder'>
<class 'torch.nn.modules.sparse.Embedding'>
<class 'torch.nn.modules.linear.Linear'>
